name: Whloot
description: A sample Polymer application
dependencies:
  dart_config: any
  intl: any
  polymer: any
  quiver: any
  xml: any
transformers:
- polymer:
    entry_points:
    - web/whloot.html
    - web/market.html
    - web/ops.html
