name: Whloot
description: A sample Polymer application
dependencies:
    polymer: any
    xml: any
    intl: any
    dart_config: any
transformers:
- polymer:
    entry_points: 
      - web/whloot.html
      - web/market.html
      - web/ops.html
